name: sfntaxi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


  #infrastructure
  provider: ^6.0.4
  logging: ^1.1.0
  easy_localization: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.2.0
  built_value: ^8.4.2
  connectivity_plus: ^3.0.2
  flutter_bloc: ^8.0.1
  logger: ^1.1.0
  chopper: ^4.0.1


  #ui
  flutter_svg: ^1.1.5
  flutter_screenutil: ^5.6.0
  flutter_easyloading: ^3.0.0
  cached_network_image: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  lint: ^1.10.0
  built_value_generator: ^8.4.2
  build_runner: ^2.3.2
  chopper_generator: ^4.0.2

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/svg/
    - assets/img/
    - assets/translations/



  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300

        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400

        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500

        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600

        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

